version: '3.7'

services:
  gateway:
    image: gateway:1.0.0
    container_name: gateway
    ports:
    - 80:80/tcp
    - 81:81/tcp
    - 443:443/tcp
    - 8000:8000/tcp
    - 8001:8001/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  test1:
    image: test1:1.0.0
    container_name: test1
  test2:
    image: test2:1.0.0
    container_name: test2
