version: '3.7'

services:
  gateway:
    image: gateway:1.0.0
    container_name: gateway
    ports:
    - 80:80
    - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#  gateway:
#    image: traefik:v2.3
#    container_name: gateway
#    command: --api.insecure=true --providers.docker
#    ports:
#    - 80:80
#    - 8080:8080
#    volumes:
#    - /var/run/docker.sock:/var/run/docker.sock
  test1:
    image: test1:1.0.0
    container_name: test1
  test2:
    image: test2:1.0.0
    container_name: test2
