log:
  level: info

entryPoints:
  web:
    address: ":80"

api:
  insecure: true
  dashboard: true

providers:
  file:
    directory: /traefik/config
    watch: true
  docker:
    exposedByDefault: false