http:
  routers:
    test2-http:
      entryPoints:
        - web
      rule: PathPrefix(`/test2`)
      service: test2-http

  services:
    test2-http:
      loadBalancer:
        servers:
          - url: http://test2:9000